import icons from "../assets/icons";

const {
  AiFillDashboard,
  AiOutlineShoppingCart,
  BiCategory,
  BiLoaderCircle,
  BiChat,
  FiUser,
  FiUsers,
  MdOutlinePayment,
  AiOutlinePlus,
  TbDiscount2,
  HiOutlineChatAlt,
  GrProductHunt,
} = icons;

export const allNav = [
  {
    id: 1,
    title: "Bảng điều khiển",
    icon: <AiFillDashboard size={20} />,
    role: "admin",
    path: "/admin/dashboard",
  },
  {
    id: 2,
    title: "Đơn Hàng",
    icon: <AiOutlineShoppingCart size={20} />,
    role: "admin",
    path: "/admin/dashboard/orders",
  },
  {
    id: 3,
    title: "Danh Mục",
    icon: <BiCategory size={20} />,
    role: "admin",
    path: "/admin/dashboard/categories",
  },
  {
    id: 4,
    title: "Seller",
    icon: <FiUser size={20} />,
    role: "admin",
    path: "/admin/dashboard/sellers",
  },
  {
    id: 5,
    title: "Yêu Cầu Thanh Toán",
    icon: <MdOutlinePayment size={20} />,
    role: "admin",
    path: "/admin/dashboard/payment-request",
  },
  {
    id: 6,
    title: "Vô hiệu hóa seller",
    icon: <FiUsers size={20} />,
    role: "admin",
    path: "/admin/dashboard/deactive-sellers",
  },
  {
    id: 7,
    title: "Kích hoạt Seller",
    icon: <BiLoaderCircle size={20} />,
    role: "admin",
    path: "/admin/dashboard/sellers-request",
  },
  {
    id: 8,
    title: "Chat Seller",
    icon: <BiChat size={20} />,
    role: "admin",
    path: "/admin/dashboard/chat-sellers",
  },
  {
    id: 9,
    title: "Bảng Điều Khiển",
    icon: <AiFillDashboard size={20} />,
    role: "seller",
    path: "/seller/dashboard",
  },
  {
    id: 10,
    title: "Thêm sản phẩm",
    icon: <AiOutlinePlus size={20} />,
    role: "seller",
    path: "/seller/dashboard/add-products",
  },
  {
    id: 11,
    title: "Sản phẩm",
    icon: <GrProductHunt size={20} />,
    role: "seller",
    path: "/seller/dashboard/products",
  },
  {
    id: 12,
    title: "Chương trình giảm giá",
    icon: <TbDiscount2 size={20} />,
    role: "seller",
    path: "/seller/dashboard/discount-products",
  },
  {
    id: 13,
    title: "Đơn hàng",
    icon: <AiOutlineShoppingCart size={20} />,
    role: "seller",
    path: "/seller/dashboard/orders",
  },
  {
    id: 14,
    title: "Thanh toán",
    icon: <MdOutlinePayment size={20} />,
    role: "seller",
    path: "/seller/dashboard/payments",
  },
  {
    id: 15,
    title: "Liên hệ KH",
    icon: <HiOutlineChatAlt size={20} />,
    role: "seller",
    path: "/seller/dashboard/chat-customers",
  },
  {
    id: 16,
    title: "Liên hệ admin",
    icon: <BiChat size={20} />,
    role: "seller",
    path: "/seller/dashboard/chat-admin",
  },
  {
    id: 17,
    title: "Hồ sơ",
    icon: <FiUser size={20} />,
    role: "seller",
    path: "/seller/dashboard/profile",
  },
];
